x_trans_menu(Clone)->0
y_trans_menu(Clone)->0
ignoreWatcher_->0
ignoreOP_->0
smartSelect_->1
autoChain_->1
handPosition_->1
handmPosition_->1
spyer_->1
resize_->0
longField_->0
*mouseParticle->1
*closeup->0
*showOff->1
*showOffWhenAct->0
*MonsterCloud->0
*Ebattle->0
*Emove->0
*Echain->0
*Ependium->0
*Exyz->0
*Esync->0
*Efusion->0
*Erution->0
*Espsum->0
*Esum->0
*Eflipsum->0
*Eset->0
*Edamage->0
*Eeqquip->0
*EactMonster->0
*EactMagic->0
*EactTrap->0
*Efield->1
*Elink->0
*Ewin->1
showoffATK->1800
showoffStar->5
x_trans_selectDeck(Clone)->13738
y_trans_selectDeck(Clone)->-137
sortByTimeDeck->1
fontSize->24
CA->272
CB->270
replayShowAll->0
reportShowAll->0
x_trans_selectServer(Clone)->0
y_trans_selectServer(Clone)->0
name->jj
x_trans_selectReplay(Clone)->0
y_trans_selectReplay(Clone)->0
sortByTimeReplay->1
x_trans_selectPuzzle(Clone)->0
y_trans_selectPuzzle(Clone)->0
x_trans_AIroom(Clone)->0
y_trans_AIroom(Clone)->0
maximize_->0
vol_->750
size_->500
vSize_->500
deckInUse->Blue Eyes
x_trans_roomSingle(Clone)->0
y_trans_roomSingle(Clone)->0
